name: DeathLabyrinth
version: '1.0.0'
main: me.zaksen.deathLabyrinth.DeathLabyrinth
api-version: '1.21'
authors: [ Zaksen_ ]

commands:
  game_status:
    description: check game status
    usage: /<command>
  game_join:
    description: join into game
    usage: /<command>
  class:
    description: class
    usage: /<command>
  give_item:
    description: give plugin item
    usage: /<command>
  reload_game:
    description: reload plugin data
    usage: /<command>
  item_tab:
    description: open tab with plugin items
    usage: /<command>
  summon_custom:
    description: summon custom entity
    usage: /<command>
  build_room:
    description: build a room from rooms folder
    usage: /<command>
  start_generation:
    description: start room generating
    usage: /<command>
  money:
    usage: /<command>